### ISSUE TITLE
Cannot complete `nix-build -A ...` more than three levels deep

### ISSUE THREAD

**Issue by bjornfor** [hedning/nix-bash-completions#11]
To reproduce, add this expression to e.g. `./test.nix`:

```
with import <nixpkgs> {};

{
  a.b.c.d.e.f.g.h = bash;
}
```

and try to complete. It will stop at the third level, like here:

```
$ nix-build ./test.nix -A a.b.c.
```

I guess it's not that common to need more than three levels in nixpkgs, but I personally could really use it for:

* Digging into nixos attrset, I would like to go deeper here: `nix-build '<nixpkgs/nixos>' -A config.system.build.`
* Some non-nixpkgs code.

**Comment by hedning** [comment]
Right, that wasn't intentional. When converting `a.b.c` to ` a b c` I unintentionally did `${foo/./ }` instead of `${foo//./ }`, the first only replaces the first match, so we'd get `a b.c`.

**Comment by bjornfor** [comment]
Wow, that was quick! Thanks!

Closing since this is fixed (I just tested it too).
