### ISSUE TITLE
Completion on available packages

### ISSUE THREAD

**Issue by trivialfis** [hedning/nix-bash-completions#5]
Hi, I installed nix 1.11.15 with `$ curl https://nixos.org/nix/install | sh` on Fedora 26 and used it to install nix-bash-completions.

After sourcing the `_nix` file, `nix-env --install <tab>` shows only the installed packages, not the available packages in the store. 

The installed version is 0.5. So I downloaded the master version f821d3a2f7afacfdb30d2eaf57f6164002c0cc84 from this github repo and tried again. The problem is still here.

**Comment by hedning** [comment]
Hi, unfortunately getting all the package names are too expensive to do on the fly so there's no name completion.

You'll want to use `nix-env --install --attr <tab>` (or `nix-env -iA <tab>` for short), to access all packages.

**Comment by hedning** [comment]
One more thing to point out which might not be obvious, when using `nix-env -iA` completion will result in `nixos` first, you'll then need to type a `.` like this: `nixos.<tab>` to complete all packages.

These things are more straightforward in ZSH as it will tell you about `--attr` in the completion help string and add and remove `.` as required. Unfortunately this isn't possible to implement in Bash as far as I know.

I'll add some notes about how attribute paths work in the readme though. Thanks for the feedback :)

**Comment by trivialfis** [comment]
Thanks. It works now.
On the other note,  `nix-env -iA <tab>` actually results in `nixpkgs` first since I'm not using NixOS's channel.
Anyway, It's nice to have completions back. Thanks.
