### ISSUE TITLE
Support for aliasing nix commands?

### ISSUE THREAD

**Issue by chreekat** [hedning/nix-bash-completions#9]
Say I would like create `alias ns=nix-shell`. Is there any way to get completion for `ns` that mimics the completion for `nix-shell`?

**Comment by chreekat** [comment]
Problems I see:

1. Rather than having separate functions for each nix command, there is a single function that inspects the command being run. It doesn't recognize my alias, naturally.
2. The underlying lazy loading also doesn't recognize `ns` as a nix command, so _nix_completion isn't even in scope unless I attempt to complete some other nix command's argument first.

**Comment by hedning** [comment]
Bash doesn't have built-in alias rewriting (this works out of the box in zsh) and https://github.com/scop/bash-completion doesn't have the feature either.

There's a pr upstream https://github.com/scop/bash-completion/pull/104/ that might work. It does the necessary work of expanding the alias and passing it to the appropriate function. If I understand correctly just put the `_complete_alias` function in your bashrc and use eg. `complete -F _complete_alias ns` to get completion for an alias.

**Comment by chreekat** [comment]
This might be the tipping point for me to switch to zsh. But I keep getting turned away by its (lack of) useful defaults and everyone's apparent dependency on oh-my-zsh... :man_shrugging:
